running with Ivan deep learning work
num_workers: 4
Using device: cuda
Using version: 2.2.1

Device name: Tesla P100-PCIE-16GB
Total memory: 15.8992919921875 GB
Allocated memory: 0.0 GB
Cached memory: 0.0 GB
Task name: unet
Epoch 1/1
----------
  0%|          | 0/46 [00:00<?, ?it/s]  0%|          | 0/46 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/Student/s4715365/testfolder/comp7840/deep_learning/segmentation/seg.py", line 406, in <module>
    train_model(model, device, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/testfolder/comp7840/deep_learning/segmentation/seg.py", line 209, in train_model
    for i, data in enumerate(tqdm(dataloader, mininterval=5)):
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 277, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 144, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 144, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 129, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 129, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Student/s4715365/anaconda3/envs/venv/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 129, in <listcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
                                    ~^^^^^
KeyError: 220

srun: error: c4130-2: task 0: Exited with exit code 1
任务失败或异常结束
